### ISSUE TITLE
Guide Document for Development Environment 

### ISSUE THREAD

**Issue by ghost** [weyoui/OpenCaster#1]
Definition of Done
- [x] : Create development guide document in WiKi.
     https://github.com/weyoui/OpenCaster/wiki/Development-Environment
- [x] :Should be tested on Linux OS. (Mint or Ubuntu)
- [x] : Should be tested on Windows OS.
- [x] : Should be tested on Mac OS.

**Comment by ghost** [comment]
Tested Done on Mint 17.3 (Rosa) .

**Comment by HansungPark** [comment]
There is no way to compile micropython libraries in windows.
So I have installed Ubuntu (16.04.1 LTS) through VMware.
Virtualbox is very similar with the VMware. But the error has occurred in my PC.
So I tried to install Ubuntu with VMware. After finishing that, I can prepare for the linux environment.
I think it's good not to consider the windows environment since now.
